FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN cd style-dictionary && npm ci && npm run build
RUN npx @11ty/eleventy && ls -d _site
RUN npx storybook build -o _site/storybook

FROM nginxinc/nginx-unprivileged:stable-alpine-slim

COPY --from=builder /app/_site/ /usr/share/nginx/html/
COPY container/nginx.conf /etc/nginx/nginx.conf
COPY container/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
