[supervisord]
nodaemon=true
user=nginx
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:vlam-host]
command=/usr/local/bin/uvicorn api:app --host 127.0.0.1 --port 8000
directory=/app/services/host
environment=PYTHONPATH="/app/services/host",PYTHONUNBUFFERED="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
